### ISSUE TITLE
Pretrained BigGAN 512?

### ISSUE THREAD

**Issue by sweidmann** [XingangPan/deep-generative-prior#11]
Hey! Thanks for the great work! I was wondering if you have a pretrained model with size 512 or a hint how the models are trained?

**Comment by XingangPan** [comment]
@sweidmann Hi, I don't have a pretrained model with size 512. I used this repo to train the BigGAN: https://github.com/ajbrock/BigGAN-PyTorch

**Comment by sweidmann** [comment]
Cool! Thanks for your answer!
