### ISSUE TITLE
What's the purpose of nll loss?

### ISSUE THREAD

**Issue by jychoi118** [XingangPan/deep-generative-prior#2]
In line 151 of models/dgp.py, you calculated and eventually added to total loss.
However, I cannot find any clue about nll loss in the paper. 
Can you tell me why you calculated nll loss?

https://github.com/XingangPan/deep-generative-prior/blob/0a21d98ec3ae23f2ccaa30f4a270fc96eb867d51/models/dgp.py#L151

**Comment by XingangPan** [comment]
@jychoi118 The nll loss is to prevent the latent vector from deviating too much from the prior gaussian distribution. This do not make much difference. We will add this in the paper.
