### ISSUE TITLE
One model per example

### ISSUE THREAD

**Issue by Yijunmaverick** [XingangPan/deep-generative-prior#3]
Great work!

Just want to clarify one point. Since you choose to fine-tune the parameters of G by using this relaxed reconstruction loss, does it imply that for each example, we need one fine-tuned BigGAN for it? Thanks.

**Comment by XingangPan** [comment]
@Yijunmaverick Yes. The BigGAN is online adapted to each target image. The fine-tuning takes about 1-2 mins.
