### ISSUE TITLE
pretrained model 'D_256' seems to be corrupted

### ISSUE THREAD

**Issue by hcwang95** [XingangPan/deep-generative-prior#5]
Thanks for publishing the code and pretrained model for the great paper!

I am not sure whether it is my problem when I download the model, but I got the size checking error for loading the pretrained model 'D_256'. However, when I switch to D_256_ch_64 and G_256_ch_64, the model loading problem disappear.

Thanks for your help!

**Comment by XingangPan** [comment]
@hcwang95 You should use --G_ch 96 --D_ch 96 instead of 64 in the training script when using the 'D_256' model.

**Comment by hcwang95** [comment]
Sorry for the ambiguity. I've tried with the flags "--G_ch 96 --D_ch 96" (by directly running "run_colorization.sh") and the loading of D_256 got an error "RuntimeError: storage has wrong size: expected 4368571749308650955 got 768". Then I switch to "run_morphing.sh" which employs the channel=64 and the model runs perfectly. 
That's why I am suspecting the 'D_256' model is corrupted.

**Comment by XingangPan** [comment]
@hcwang95 I have tried again with the 'D_256' model in the google drive folder, and it runs well without error. Could it be a pytorch version issue? I am using pytorch1.1.

**Comment by hcwang95** [comment]
Sure. Thanks a lot for helping to test the model file. I will check the torch==1.1 and get back to you soon!

**Comment by hcwang95** [comment]
It looks like the error is still there. I am almost sure that it is because of the corrupted model file. But I tried several times to download the D_256 and found the error didn't change. 

But @XingangPan thank you for your kind help in checking the model file. As long as it is without any problem on your side and no others find similar problem, I will close the issue here since it seems to be the rare problem only happens to me.

Thanks!
