### ISSUE TITLE
About G.eval()

### ISSUE THREAD

**Issue by wtybest** [XingangPan/deep-generative-prior#8]
Congratulations on your excellent work! In your code, I notice you set generator to eval() mode when you fine-tune the bigGAN, I wonder if it's necessary to set generator to eval() mode when we fine tune it.

**Comment by XingangPan** [comment]
@wty-ustc It is necessary to set generator to eval() mode, because otherwise the mean and var parameters in BN or IN would be inaccurate, and the output is likely to be unreasonable.
